<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WaiversTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         $table = DB::table('waivers');

         $html = "WAIVER OF LIABILITY, RELEASE, ASSUMPTION OF RISK & INDEMNITY AGREEMENT
IT IS THE PURPOSE OF THIS AGREEMENT FOR THE PARTICIPANT (AND PARTICIPANT'S PARENT(S)/GUARDIAN(S), IF APPLICABLE) TO EXEMPT, WAIVE AND RELIEVE RELEASEES FROM LIABILITY FOR PERSONAL INJURY, PROPERTY DAMAGE, AND WRONGFUL DEATH, INCLUDING IF CAUSED BY NEGLIGENCE, INCLUDING THE NEGLIGENCE, IF ANY, OF ANY RELEASEES.
\"Releasees\" include USA Hockey, Inc., its affiliate associations, local associations, member teams, event hosts, other participants, coaches, officials, sponsors, advertisers, and each of them, their officers, directors, agents and employees.
For and in consideration of the undersigned Participant's registration with USA Hockey, Inc., its affiliates, local associations and member teams (all referred to together as USAH) and being allowed to participate in USAH events and member team activities, Participant (and the parent(s) or legal guardian(s) of Participant, if applicable) waives, releases and relinquishes any and all claims for liability and cause(s) of action, including for personal injury, property damage or wrongful death occurring to Participant, arising out of participation in USAH events, member team activities, the sport of ice hockey, and/or activities incidental thereto, whenever or however they occur and for such period said activities may continue, and by this agreement any such claims, rights, and causes of action that Participant (and Participant's parent(s) or legal guardian(s), if applicable) may have are hereby waived, released and relinquished, and Participant (and parent(s)/guardian(s), if applicable) does(do) so on behalf of my/our and Participant's heirs, executors, administrators and assigns.
Participant (and Participant's parent(s)/guardian(s), if applicable) acknowledges, understands and assumes all risks relating to ice hockey and any member team activities, and understands that ice hockey and member team activities involve risks to Participant's person including bodily injury, partial or total disability, paralysis and death, and damages which may arise therefrom and that I/we have full knowledge of said risks. These risks and dangers may be caused by the negligence of the Participant or the negligence of others, including the \"Releasees\" identified above.  These risks and dangers include, but are not limited to, those arising from participating with bigger, faster and stronger participants, and these risks and dangers will increase if Participant participates in ice hockey and member team activities in an age group above that which Participant would normally participate in.  Participant (and Participant's parent(s)/guardian(s), if applicable)  further acknowledges that there may be risks and dangers not known to us or not reasonably foreseeable at this time. Participant (and Participant's parent(s)/guardian(s), if applicable) acknowledge, understand and agree that all of the risks and dangers described throughout this agreement, including those caused by the negligence of Participant and/or others, are included within the waiver, release and relinquishment described herein. 
Participant (and participant's parent(s)/guardian(s), if applicable) acknowledges, understands and assumes the risks, if any, arising from the conditions and use of ice hockey rinks and related premises and acknowledges and understands that included within the scope of this waiver and release is any cause of action (including any cause of action based on negligence) arising from the performance, or failure to perform maintenance, inspection, supervision or control of said areas and for the failure to warn of dangerous conditions existing at said rinks, for negligent selection of certain Releasees, or negligent supervision or instruction by any Releasee.
As a condition of registration and membership in USA Hockey and participation in USAH events and member team activities, Participant (and Participant's parent(s)/guardian(s), if applicable) agrees to abide by and be bound under the playing rules and rules and regulations of USA Hockey, including the By-Laws of USA Hockey and the mandatory dispute resolution, discipline and arbitration provisions, as currently published in the USA Hockey Annual Guide. Copies of the USA Hockey Bylaws, including the mandatory dispute resolution, discipline and arbitration clauses, are available from the USA Hockey offices or may be found at www.usahockey.com/annualguide.  Any dispute, claim or cause of action regarding the terms of this agreement or subject matter hereof shall be brought (i) individually, without resort to any form of class or collective action, and without joinder or consolidation of claims of third parties, and (ii) exclusively in the manner provided in the rules of USA Hockey (including, without limitation USA Hockey Bylaw 10) to the extent applicable.
As further consideration for registration and participation in USAH events and member team activities, Participant (and the parent(s) or legal guardian(s) of participant, if applicable), hereby (1) consents and agrees that USAH, its licensees and designees may make video and/or audio recordings of and/or otherwise film, photograph or memorialize some or all of Participant's participation in such events and activities, and (2) grants to USAH, its licensees, designees, successors and assigns, a worldwide, perpetual, irrevocable, fully-paid, royalty-free, transferable and sublicenseable right and license to use, copy and disseminate Participant's image and personal attributes, and to modify and present same in any form, manner and media, now known or hereafter devised, for any purpose whatsoever.
If the law in any controlling jurisdiction renders any part of this agreement unenforceable, the remainder of this agreement shall nevertheless remain enforceable to the full extent, if any, allowed by controlling law. This agreement affects your legal rights, and you may wish to consult an attorney concerning this agreement.
Participant (and Participant's parent(s)/guardian(s), if applicable) agree if any claim for Participant's personal injury or wrongful death is commenced against any Releasee, he/she shall defend, indemnify and save harmless Releasees from any and all claims or causes of action by whomever or wherever made or presented for Participant's personal injuries, property damage or wrongful death.
Participant (and Participant's parent(s)/guardian(s), if applicable) acknowledge that they have been provided and have read the above paragraphs and have not relied upon any representations of Releasees, that they are fully advised of the potential dangers of ice hockey, that they agree to and sign this document voluntarily, understanding that these waivers and releases are necessary to allow amateur ice hockey to exist in its present form. Significant exclusions may apply to USA Hockey's insurance policies, which could affect any coverage. For example, there is no liability coverage for claims of one player against another player. Read your brochure carefully and, if you have any questions, contact USA Hockey or a District Risk Manager.
								";

         $values = [
             'html' => $html,
             'status'=>true,
         ];

        $table->insert($values);
    }
}
